# -*- coding: utf-8 -*-
"""Activitat7Example

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RvNVKvOeRXdWL-7_lFxpWcml1MXD9u-p
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd 
df = pd.read_csv("students_grades.csv")

mitjana = df["grades"].mean()
mediana = df["grades"].median()

print("""
Mitjana: %d
Mediana: %d
"""%(mitjana,mediana))

import seaborn as sns
import matplotlib.pyplot as plt

x = ["UF1","UF2","UF3"]
y = [mitjana,mediana,9]

plt.bar(x,y)
plt.show()

import csv
with open("students_grades.csv", newline='') as File:
  reader = csv.reader(File)
  for row in reader:
    print(row)

data = pd.read_csv("students_grades.csv")
data["grades"].values

name = input("Enter name ")
print(name)

num1 = int(input())
num2= int(input())

print (num1+num2)

import matplotlib.pyplot as plt

UF =[10,15,20,25]
UFsName = ["UF1","UF2","UF3","UF4"]
plt.pie(UFs, labeldistance==UFsNames,autopct="%0.1f %%")
plt.axis("equal")
plt.show()